package tiktokmapi

import (
	"errors"
	"net/url"
	"strings"
)

// PrepareAuthorizationURL adds a host-generated one-time state to the exact
// advertiser authorization URL copied from TikTok My Apps. It does not invent
// an authorization endpoint or change any other portal-generated parameter.
func PrepareAuthorizationURL(raw, redirectURL, state string) (string, error) {
	if raw == "" || len(raw) > 8192 || redirectURL == "" || len(state) < 40 || len(state) > 128 || strings.ContainsAny(raw+state, "\r\n") {
		return "", errors.New("invalid TikTok advertiser authorization URL")
	}
	u, err := url.ParseRequestURI(raw)
	if err != nil || u.Scheme != "https" || u.User != nil || u.Fragment != "" {
		return "", errors.New("invalid TikTok advertiser authorization URL")
	}
	switch strings.ToLower(u.Hostname()) {
	case "business-api.tiktok.com", "ads.tiktok.com":
	default:
		return "", errors.New("authorization URL must be generated by TikTok My Apps")
	}
	if u.Port() != "" || u.Path == "" || u.Path == "/" {
		return "", errors.New("invalid TikTok advertiser authorization URL")
	}
	q := u.Query()
	for _, key := range []string{"secret", "app_secret", "access_token", "auth_code"} {
		if _, exists := q[key]; exists {
			return "", errors.New("authorization URL contains a forbidden credential parameter")
		}
	}
	if values := q["redirect_uri"]; len(values) > 1 || len(values) == 1 && values[0] != redirectURL {
		return "", errors.New("authorization URL redirect does not match --redirect-url")
	}
	if len(q["state"]) > 1 {
		return "", errors.New("authorization URL contains multiple state parameters")
	}
	q.Set("state", state)
	u.RawQuery = q.Encode()
	return u.String(), nil
}
